### ISSUE TITLE
Use `numa_sched_setaffinity` to bind pthread object into each CPU-thread

### ISSUE THREAD

**Issue by nikezono** [LineairDB/LineairDB#238]
LineairDB’s inner thread pool spawns pthread objects and uses a lock-free thread-local queue to distribute tasks, but the thread objects are sometimes wakened up from irrelevant CPU threads.
This is because the os kernel does not know the bindings between pthread object and CPU thread.

reference: https://man7.org/linux/man-pages/man3/numa.3.html

**Comment by oza** [comment]
@nikezono FYI, you can also use [numa_alloc_onnnode](https://linux.die.net/man/3/numa_alloc_onnode) or other related functions to enable threads' to use local region. However, I don't know how to use a custom memory allocator for smart pointers or classes in C++. [This stackoverflow's discussion](https://stackoverflow.com/questions/9521226/c-stl-with-jemalloc) might be useful.
